[General]
noauth=true
unpack=true
bootstrap=Ports
aptsources=Ports

[Ports]
packages=libc6-dev libstdc++-14-dev libc++-14-dev libxext-dev libxtst-dev libgles-dev libibus-1.0-dev libudev-dev
source=http://ports.ubuntu.com
suite=noble
components=main universe